stages:
  - build
  - test

build:linux:
  stage: build
  tags:
    - docker
    - build
  image: ubuntu:20.04-build
  script:
    - mkdir build && cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DCOVERAGE_ENABLED=ON -DADDRESS_SANITIZER_ENABLED=ON
    - cmake --build .
  artifacts:
    paths:
      - build/
      - build/tests

test:linux:
  stage: test
  tags:
    - docker
    - test
  image: ubuntu:20.04-build
  script:
    - cd build
    - cmake --build . --target coverage
    - cd ..
    - gcovr --xml-pretty --print-summary --exclude-unreachable-branches -e .deps -e tests -e benchs -o coverage.xml --root .
    - replace-content --file=build/junit-report.xml --replace=${CI_PROJECT_DIR}/
  dependencies:
    - build:linux
  coverage: /^\s*lines:\s*\d+.\d+\%/
  artifacts:
    name: ${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    paths:
      - build/coverage
      - build/junit-report.xml
    reports:
      cobertura: coverage.xml
      junit: build/junit-report.xml

build:windows:
  stage: build
  tags:
    - windows
    - build
  script:
    - mkdir build 
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release .. 
    - cmake --build .
  artifacts:
    paths:
      - build/Debug/tests.exe

test:windows:
  stage: test
  tags:
    - windows
    - test
  script:
    - cd build/Debug
    - ./tests.exe --gtest_output=xml:junit-report.xml --gtest_print_file_info
    - cd ../..
  dependencies:
    - build:windows
  artifacts:
    name: ${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    paths:
      - build/Debug/junit-report.xml
    reports:
      junit: build/Debug/junit-report.xml

build:arm32v5:21.07.15:
  stage: build
  image: ubuntu-arm32v5:21.07.15
  script:
    - mkdir build && cd build
    - cmake .. -DCMAKE_TOOLCHAIN_FILE=$TOOLCHAIN_FILE -DCMAKE_BUILD_TYPE=Release
    - cmake --build .
  artifacts:
    paths:
      - build/
      - build/tests

# benchmark-job:
#   stage: test
#   image: ubuntu:20.04-build
#   script:
#     - ./build/benchs
