[package]
name = "nhope"

[lib]
lang = "c++20"

[[test]]
lang = "c++20"
path = "tests"

[[test]]
lang = "c++20"
path = "benchs"

[dependencies]
asio = {git = "git@gitlab.olimp.lan:github/standalone-asio.git", tag = "asio-1-20-0", interface = "asio/include"}
fmt = {git = "git@gitlab.olimp.lan:github/fmtlib.git", tag = "7.1.3"}

[dev-dependencies]
benchmark = {git = "git@gitlab.olimp.lan:github/benchmark.git"}
gtest = {git = "git@gitlab.olimp.lan:google/googletest.git"}

[dependencies.windows-specific]
path = "specific/windows"
system = "Windows"

[dependencies.linux-specific]
path = "specific/linux"
system = "Unix"

[options.gtest]
gtest_force_shared_crt = "true"

[options.benchmark]
BENCHMARK_ENABLE_GTEST_TESTS = "false"
BENCHMARK_ENABLE_TESTING = "false"
