[package]
name = "nhope"

[lib]
lang = "c++17"

[[test]]
lang = "c++17"
path = "tests"

[dependencies]
asio = { git = "git@gitlab.olimp.lan:github/standalone-asio.git", tag = "asio-1-18-1", interface = "asio/include" }

[sys-dependencies.Boost]
components = [ "thread", "chrono" ]

[dev-dependencies]
gtest = { git = "git@gitlab.olimp.lan:google/googletest.git" }
