[package]
name = "nhope"

[lib]
lang = "c++17"

[[test]]
lang = "c++17"
path = "tests"

[[test]]
lang = "c++17"
path = "benchs"

[dependencies]
asio = {git = "git@github.com:chriskohlhoff/asio.git", tag = "asio-1-28-0", interface = "asio/include"}
fmt = {git = "git@github.com:fmtlib/fmt.git", tag = "9.1.0"}
gsl = {git = "git@github.com:microsoft/GSL.git", tag = "v4.0.0", interface = "include"}

[dev-dependencies]
benchmark = {git = "git@github.com:google/benchmark.git", branch = "main"}
gtest = {git = "git@github.com:google/googletest.git", branch = "main"}

[dependencies.windows-specific]
path = "specific/windows"
system = "Windows"

[dependencies.linux-specific]
path = "specific/linux"
system = "Unix"

[options.gtest]
gtest_force_shared_crt = "true"

[options.benchmark]
BENCHMARK_ENABLE_GTEST_TESTS = "false"
BENCHMARK_ENABLE_TESTING = "false"
