[package]
name = "nhope"

[lib]
name = "nhope"
lang = "c++17"

[sys-dependencies.Boost]
components = [ "chrono", "system", "thread" ]

[dev-dependencies]
gtest = { git = "git@gitlab.olimp.lan:google/googletest.git" }
